FROM python:3.11-slim

WORKDIR /app


ARG REDIS_URL
ARG BINANCE_BASE_URL
ARG BINANCE_WS_BASE_URL
ARG CORS_ALLOW_ORIGINS
ARG RATE_LIMIT_PER_MINUTE
ARG JWT_SECRET_KEY
ARG JWT_ALGORITHM
ARG JWT_ACCESS_TOKEN_EXPIRE_MINUTES
ARG MARKET_WS_INTERVAL_SECONDS
ARG KPI_WS_INTERVAL_SECONDS
ARG GLOBAL_EXPOSURE_THRESHOLD
ARG MAX_LEVERAGE
ARG BINANCE_API_KEY
ARG BINANCE_API_SECRET


ENV REDIS_URL=${REDIS_URL}
ENV BINANCE_BASE_URL=${BINANCE_BASE_URL}
ENV BINANCE_WS_BASE_URL=${BINANCE_WS_BASE_URL}
ENV CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}
ENV RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE}
ENV JWT_SECRET_KEY=${JWT_SECRET_KEY}
ENV JWT_ALGORITHM=${JWT_ALGORITHM}
ENV JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
ENV MARKET_WS_INTERVAL_SECONDS=${MARKET_WS_INTERVAL_SECONDS}
ENV KPI_WS_INTERVAL_SECONDS=${KPI_WS_INTERVAL_SECONDS}
ENV GLOBAL_EXPOSURE_THRESHOLD=${GLOBAL_EXPOSURE_THRESHOLD}
ENV MAX_LEVERAGE=${MAX_LEVERAGE}
ENV BINANCE_API_KEY=${BINANCE_API_KEY}
ENV BINANCE_API_SECRET=${BINANCE_API_SECRET}

COPY requirements.txt .
RUN pip install --no-cache-dir --default-timeout=120 -r requirements.txt

COPY app/ ./app/

WORKDIR /app/app

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
